# Generated by Django 5.0.7 on 2024-10-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_at',
            field=models.DateTimeField(null=True),
        ),
    ]
