# Generated by Django 5.0.7 on 2024-10-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_payment_pay_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle_type',
            new_name='VehicleType',
        ),
    ]
