# Generated by Django 5.1.1 on 2024-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_vehicle_image_url_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(default='111', max_length=10),
            preserve_default=False,
        ),
    ]
