# Generated by Django 5.1.1 on 2024-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slip',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
    ]
