# Generated by Django 5.1.1 on 2024-10-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_remove_payment_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.employee'),
        ),
    ]
